fix: flask-session incompatibility
Update to latest Flask-Session to fix an issue with using
server-side user sessions.  This is being caused by Superset
4.0.2 using Werkzeug 3.0.0, which is not compatible with
Flask-Session 0.5.0.

The error being thrown on server start up is:
```
TypeError: cannot use a string pattern on a bytes-like object
```